[build-system]
requires = ["setuptools~=67.7.2", "wheel~=0.41.3", "pip~=23.3.1", "setuptools_scm[toml]~=7.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/version.py"